# Generated by Django 5.1.4 on 2025-05-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('form', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('level', models.CharField(choices=[('ordinary level', 'Ordinary level'), ('advanced level', 'Advanced level')], max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='Male', max_length=7)),
                ('form', models.CharField(choices=[('1E', '1E'), ('1W', '1W'), ('1N', '1N'), ('1S', '1S'), ('2E', '2E'), ('2W', '2W'), ('2N', '2N'), ('2S', '2S'), ('3E', '3E'), ('3W', '3W'), ('3N', '3N'), ('3S', '3S'), ('4E', '4E'), ('4W', '4W'), ('4N', '4N'), ('4S', '4S'), ('5S', '5S'), ('5C', '5C'), ('5A', '5A'), ('6S', '6S'), ('6C', '6C'), ('6A', '6A')], max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('ordinary level', 'Ordinary level'), ('advanced level', 'Advanced level')], max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='borrowed', max_length=10)),
                ('updated_at', models.DateField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='base.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='base.student')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.CharField(help_text='Reason for the fine (e.g., overdue, lost book, damaged book).', max_length=255)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=6)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='base.borrow')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.shelf'),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subject'),
        ),
    ]
