# Generated by Django 5.1.4 on 2025-05-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='Male', max_length=7),
        ),
    ]
